# baseURL = "https://EddieAbbondanzio.github.io/"
baseURL = "https://eddieabbondanz.io"
languageCode = "en-us"
title = "Eddie Abbondanzio"
theme = "blank"
author = "Eddie Abbondanzio"
copyright = "&copy; 2019. All rights reserved."
canonifyurls = true
paginate = 10
googleAnalytics = "UA-128571017-1"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "monokai"
summaryLength = 30

[markup.goldmark.renderer]
unsafe= true

[taxonomies]
    series = "series"

[params]
    avatar = "/img/avatar.jpg" # Image should be square, and roughly 150px x 150px
    bio = "My name's Eddie Abbondanzio, and this is my blog. I mostly write about game dev / web dev, but I'll throw in the occasional car post."
    github = "http://github.com/EddieAbbondanzio"
    twitter = "https://twitter.com/EAbbondanzio"
    description = "I build things. Sometimes good."


[menu]
    [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "post"
    weight = 1

    [[menu.main]]
    name = "Development"
    identifier = "development"
    parent = "posts"
    url="series/development"

    [[menu.main]]
    name = "XJ Build"
    identifier = "xj-build"
    parent = "posts"
    url="series/xj-build"

    [[menu.main]]
    identifier = "about-me"
    name = "About Me"
    url = "about"
    weight = 2

    [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "portfolio"
    weight = 3
